### ISSUE TITLE
CSRF tokens should not be required for stateless HTTP methods

### ISSUE THREAD

**Issue by bts** [plow-technologies/servant-auth#10]
Hi there,

Thank you for this library!

I've noticed that CSRF tokens seem to be required for `GET`, `HEAD`, `OPTIONS`, and `TRACE` requests, but these methods should never change any state, so they are safe to be performed without a token.

See:
- https://docs.spring.io/spring-security/site/docs/3.2.7.RELEASE/apidocs/org/springframework/security/web/csrf/CsrfFilter.html
- https://elithrar.github.io/article/preventing-csrf-attacks-in-go/
- https://docs.djangoproject.com/en/1.7/ref/contrib/csrf/

I'm submitting another issue shortly, and I am going to try to help out with these issues.

**Comment by jkarni** [comment]
My inclination is to keep `GET` CSRF-protected, for a few reasons:

1) APIs with state-changing `GET` endpoints aren't rare, even if not best practice. It seems unnecessary in this case to predicate security on following a best practice that not everyone follows;
2) If `GET`s refresh tokens (a side-effect that, like logging a request, usually gets brushed under the rug as acceptable and normal for a request to have), CSRF attacks can be used to keep cookies fresh, negating the added security measure that e.g. banks have of logging out the user quickly;
3) It just seems like a historical accident (coming from the fact that traditionally CSRF-protection happened in forms) that people assume only POST is protected

But if you think there are downsides to this, do let me know!

(For what it's worth, the OWASP page does mention CSRF attacks in GET requests [0])

For the other methods, things might be more complicated, since these are often the result of automated requests (e.g., pre-flight `OPTIONS`). I'm not sure what to think about those.

[0] https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by bts** [comment]
Yeah I agree with you -- might as well just require CSRF tokens on all browser requests. Thanks for taking a look at this.
