### ISSUE TITLE
Cookie Auth broken?

### ISSUE THREAD

**Issue by Akii** [plow-technologies/servant-auth#28]
Hi!

```
curl -v --cookie "JWT-Cookie=eyJhbGciOiJIUzI1NiJ9.eyJkYXQiOnsiZW1haWwiOiJhbGlAZW1haWwuY29tIiwibmFtZSI6IkFsaSBCYWJhIn19.U-PyzI3wJgmJA-aiRl_vH6Ij9l0XN3AmmjP_NtNnolk" http://localhost:7249/name
*   Trying ::1...
* connect to ::1 port 7249 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7249 (#0)
> GET /name HTTP/1.1
> Host: localhost:7249
> User-Agent: curl/7.43.0
> Accept: */*
> Cookie: JWT-Cookie=eyJhbGciOiJIUzI1NiJ9.eyJkYXQiOnsiZW1haWwiOiJhbGlAZW1haWwuY29tIiwibmFtZSI6IkFsaSBCYWJhIn19.U-PyzI3wJgmJA-aiRl_vH6Ij9l0XN3AmmjP_NtNnolk
> 
< HTTP/1.1 401 Unauthorized
< Transfer-Encoding: chunked
< Date: Sat, 11 Feb 2017 15:11:50 GMT
< Server: Warp/3.2.9
< 
* Connection #0 to host localhost left intact
```

Using the readme tutorial, after successfully logging in.
It works using the same file with the JWT option.

Any idea how to debug this further?

**Comment by bts** [comment]
I think you need to set CSRF tokens both at the header and cookie level:

curl -v **-H "X-XSRF-TOKEN: csrftokengoeshere"** -H "Cookie: JWT-Cookie=eyJhbGciOiJIUzI1NiJ9.eyJkYXQiOnsiZW1haWwiOiJhbGlAZW1haWwuY29tIiwibmFtZSI6IkFsaSBCYWJhIn19.U-PyzI3wJgmJA-aiRl_vH6Ij9l0XN3AmmjP_NtNnolk; **XSRF-TOKEN=csrftokengoeshere**" -H "Accept: application/vnd.api+json" "http://localhost:7249/name"

In order to get a CSRF token you might need the new function introduced in #27, but you should see a related question I've just asked in #30.

**Comment by Akii** [comment]
That's weird. Should not be required for safe requests. I'll checkout #30 and #27!

**Comment by jkarni** [comment]
The reasoning for having it be required for stateless requests is discussed in #10 . I'm closing, but if you think that's a mistake, please feel free to re-open!

**Comment by Akii** [comment]
Good reasoning, I very much approve; never thought about this. One thing though: Why is this not required for JWT? Sending the 'Authorize' header does not require XSRF the token. Is it because this is not intended to be used in a "Browser"?

**Comment by Akii** [comment]
I'll try to expand the readme to reflect this insight asap (probably tomorrow (famous last words)).

**Comment by jkarni** [comment]
>  Is it because this is not intended to be used in a "Browser"?

Exactly. In which case there's no CSRF concerns.
