### ISSUE TITLE
Question about login response 

### ISSUE THREAD

**Issue by rikvdkleij** [plow-technologies/servant-auth#38]
Looking to the example code in the readme, I wonder if it's possible to not respond with token in cookie but to return a JSON object in the repsonse body which contains the token?

When I change:
```
 let jwtCfg = defaultJWTSettings myKey
      cfg = defaultCookieSettings :. jwtCfg :. EmptyContext
      --- Here we actually make concrete
      api = Proxy :: Proxy (API '[JWT])
``` 
to 
```
 let jwtCfg = defaultJWTSettings myKey
      cfg =  jwtCfg :. EmptyContext
      --- Here we actually make concrete
      api = Proxy :: Proxy (API '[JWT])
```
I  get this error:
`No instance for (HasContextEntry '[] CookieSettings)
        arising from a use of ‘serveWithContext’
`

**Comment by rikvdkleij** [comment]
I noticed that adding the `defaultCookieSettings` to the context without using cookie for the login response and authentication just works.
The implementation of `HasServer (Auth auths v :> api) ctxs` demands that `CookieSettings` are also have to be in context for the `authCheck`. 
I do not understand that because in readme:
> What Auth [Auth1, Auth2] Something :> API means is that API is protected by either Auth1 or Auth2, and the result of authentication will be of type AuthResult Something`

**Comment by jkarni** [comment]
Someone was asking about this just yesterday in the servant IRC channel. Right now authentication options always send `Set-Cookie` headers, *even if they don't accept cookies*. This is basically because in the original design that was just easier to implement, but now things have changed sufficiently that it shouldn't be a problem to fix it.

For now you should use the `defaultCookieSettings`, mutter curses at me every time you see the code, and it should work. 

Note however that `JWT` uses response headers, *not* the response body. We could have a different authentication type that uses the body - it would simplify login by just making it a different kind of authentication - though there are some performance concerns (we have to keep the entire body in memory in the naive implementation).

**Comment by rikvdkleij** [comment]
@jkarni Thanks for your reply.
I have joined Servant's IRC channel. It's a pity that Servant's archive on IRCBrowse is not available.

It would be cool if it's get fixed.

Because the application I working on is "machine-to-machine" communication, it makes more sense to return JSON object which contains token and for example also expiration datetime if login is successful. The subsequent calls put this token in request authorization header.
To my knowledge `JWT` does not enforce you to return token in response header.
